# Generated by Django 3.0.3 on 2020-03-03 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='cvfile',
            field=models.FileField(upload_to=''),
        ),
    ]
